### PR TITLE
Music support

### PR DESCRIPTION
**Pull request by yeahme49**
This adds some basic music support

"Play artist The Beatles on kitchen speaker"
"Play track Love Me Do on kitchen speaker"
"Play album Revolver on kitchen speaker"
"Play random artist The Beatles on kitchen speaker"

Have not tested with music playlists yet and you need to specify if you wanting an artist, track or album. It doesn't test for them in find_media like shows and movies do with fuzzywuzzy.

I've thought about making the default for artist to be shuffle, since I would assume if you want to listen to an artist you'd want random songs from that artist. Maybe make it an option to choose the default setting for artist.

Feel free to make any suggestions or changes.

- [x] Fuzzy search
- [x] Album by Artist
- [x] Playlist
- [x] Sonos devices
- [x] Localizations

### CODE REVIEW

**Comment by maykar** [comment]
This is a great start, thank you. I need to add some music to my sever for some testing and there are a few things I'd like to be included before pulling and will help as soon as I can.

* Fuzzy search should be included so `artist, track or album` keywords aren't required
* Need to handle things with a new separator like `play revolver "by" the beatles`
* Playlist support (should be easy enough and would work with video playlists too)
* Add Sonos devices (small change, they accept the same payload as google cast devices)
* Small changes to the localizations

**Comment by maykar** [comment]
Also, sorry for the continued changes to the master branch. There are a handful of bugs I need to squash before I start working on this.

**Comment by yeahme49** [comment]
One other thing I'd like to try and do, but I'm not sure if it's possible. If you ask for music to be played, have it play on the speaker the request comes from without having to name a device or using the default device. I have a couple google devices i like to play music on and it would be easier to have the music play on the device i'm using instead of having to name one. I just don't know if there is anything that indicated which speaker the request comes from

**Comment by maykar** [comment]
IFTTT doesn't provide that information so it wouldn't be possible with that trigger option. There may be a way to do this with DialogFlow, but I haven't really looked into it as DialogFlow is pretty convoluted as it is and will always respond "Talking to the test version of Plex"

**Comment by maykar** [comment]
Think I've found a solution to the next/previous issue, I'm polling the plex media_players to find the one that matches the chromecast so I can return the PlexAPI client object to use it's commands instead. Unfortunately, I now have three 6 year olds that have taken over the TV so I can't fully test, but will later tonight.

**Comment by maykar** [comment]
Let me know if that refactored find_media function is working for you. At work all day and the family has a snow day, so any testing I do will disrupt their entertainment.

**Comment by yeahme49** [comment]
The new find_media seems to work in my testing. I'm not sure if certain library types should be weighted higher. Like if I do "Play the beatles", i get the same score for both album and artist due to them having an album called the beatles. My opinion would be if you aren't specifying what you are searching, it should default to artist over album. Or maybe respond back saying there was multiple matches and to be more specific?

**Comment by maykar** [comment]
Unfortunately, responses for clarification aren't really an option, but I just changed the order of the items returned in find media. Now if any match has the same score then it will choose in that order of importance: `["show", "movie", "artist", "album", "track"]`.

**Comment by maykar** [comment]
Responses for clarification would only be available for DialogFlow as IFTTT doesn't have that ability. Even if we went that roiute DialogFlow would need an major overhaul and require me to do a bunch of research. It would require the DialogFlow action to be aware of what device you're talking to and the logic to handle responses from HA. Not sure if either of those things are possible without publishing the action/app and if it's published I don't know if a variable webhook can be used (necessary for HA) and we wouldn't be able to use the name "Plex" as it's a company's name and Google blocks that for anyone other than the orginization.

**Comment by maykar** [comment]
Don't mind strange small changes, doing it to make merging master easier for upcoming changes.

**Comment by maykar** [comment]
I think we're pretty close here. I'll double check the localizations and add music to my library for some full testing, but I think this can go into the next release and I'll just make a feature request for `play track name by artist name` and `play album name by artist name`.

**Comment by maykar** [comment]
Sorry, I shouldn't be making all these changes on your branch here, but accommodating music caused one thing to lead to another and so on.

**Comment by maykar** [comment]
Merged and released, may thanks for the help and getting this started, as well as putting up with the many notifications and master merges. Really appreciate it!

**Pull request merged**
