### PR TITLE
Adding Danish language-support

### PR DESCRIPTION
**Pull request by exetico**
Let me know, if you find any issues. Danish is a bit wierd, so I've tried to do my best. The usage of "the" is normally removed in most titles in the Danish version of the media-title.

### CODE REVIEW

**Comment by maykar** [comment]
Fixed the formatting and removed comments. The first "play" option can only be one item at the moment, I may update that and other options to accept multiple at some point. The ordinal section's "pre" was still set as "the", I used the translation from the other pull request of "den".

Look alright? Have you given this a test on your system, if not would you mind giving it a try? Just replace the `localize.py` on your system set "da" in your language config for plex assistant and restart.

**Comment by exetico** [comment]
Sure, I can try and give it a go. I've also tried to the the english version to work as expected - there's separate issue for that part.

I'll try and replace the file and test with only da-DK selected in all settings - I'll get back in a bit of time.

**Comment by exetico** [comment]
It looks fine from my end,  @maykar  . I think i misunderstood the meaning of the "pre" for both episode end season, and I've also connected a few things based on the other translations. Most of the corrections in that commit make sense too. There's just far more ways to say most of the things in Danish.

I'm also not that sure about the "on desk". Is that the things present on the home-screen of Plex, ready to be played? (So it can pick-up the element, based on previous playback history in Plex)....

Let me know if I've missed something. And if my editor has messed with the formatting again. Normally I'm just asking it to format it on every save.

**Comment by maykar** [comment]
Sorry for taking so long to respond. Formatting looks fine.

It's "on DECK" not "on DESK" and yes, that is the section of plex where it suggest what you should play next based on history. I'll fix the english versions of "on deck" in your translation now, but let me know if the translated version is still okay or if you want to change it.

**Comment by exetico** [comment]
It's fine 👍 Feedback can come down the line, if someone has it.

The Danish version are working as it should, om my machine.

**Pull request merged**
