### PR TITLE
Add Rhasspy Voice Assistant Guide

### PR DESCRIPTION
**Pull request by gfawkes66**
Hello, i have added a section for Rhasspy voice assistant as requested.
any comments welcome

### CODE REVIEW

**Comment by maykar** [comment]
I apologize in advance as I haven't tried Rhasspy yet, but I will install to check this out later this week (hopefully).

Why wouldn't you just use the sentence:
```
[PlexCommand]
tell plex to {plex_command}
```

With an automation like:
```
  trigger:
    - platform: event
      event_type: rhasspy_PlexCommand
  action:
    - service: plex_assistant.command
      data_template:
        command: '{% trigger.event.data.plex_command %}'
```

**Comment by maykar** [comment]
Would that remove the need for providing a list of media items and keep all of Plex Assistants functionality?

**Comment by gfawkes66** [comment]
Hi, yes that is a much more elegant solution. But There are a couple of problems as you might imagine!
1) Here's to hoping i can articulate this!. 
tell plex to {plex_command} - the way this works is that it passes the value just before {plex_command}, so your example will pass 'to' as the value unfortunately. 
In my example i have setup $films and populated it with a list of films. Placing this just before the variable means that the film is passed over. 
Your way would be much more efficient code wise and remove the necessity to maintain a list of films, as well as providing access to other commands. The problem might be that when you save sentences and slots in Rhasspy, they are 'trained' or learnt, including my list of films. 
I have not seen a way of putting unknown/undefined text in to a variable/ tag, probably for the reason i have just outlined. 
That said I may post a question on the Rhasspy forum to see if this is possible or that i have interpreted correctly because testing your example does trigger and send the whole sentence over, just not populating the plex_command tag as you would hope.
2) command: '{% trigger.event.data.plex_command %}'
This might be me running out of talent, as i have never managed to get this to work without the extra step, and its also the case with your syntax which wont save. 
I have always had to use 
command: '{% set plex_command = trigger.event.data.plexcommand %} {{ plex_command }}'
ie, i have not managed to simplify this....

So, as you say it may be best to take a few days to try and refine this. I will post on Rhasspy and see what they say.
If you decide to install it, i would recommend the docker solution. Beware though, you may end up down a rabbit hole!

**Comment by gfawkes66** [comment]
Hi,

Well a mixed bag of an answer.

If you are not familiar with Rhasppy, it is like a toolbox. ie you can make choices as to which modules perform different functions making it infinitely configurable.

I put a post in the Rhasspy forum and it has been suggested that if i use 'Snips NLU' for the intent recognition then this module has the ability to identify/ pass undefined text. The bad news is that there are currently issues with arm processor compatibility and also with the engine itself. It has been temporarily pulled from Rhasspy pending fixes. I'll investigate the module when its fixed and see if its simple enough to configure. Other posts suggest that it seems like it may not be too long before its fixed.

My Rhasspy post:-
https://community.rhasspy.org/t/passing-undefined-text-in-a-sentance/1319

**Pull request closed without merging**
